name: Manual Trigger Build

on:
  workflow_dispatch:
    inputs:
      buildType:
        type: choice
        description: Select Build type
        required: true
        default: 'debug'
        options:
          - debug
          - release

      version:
        type: build_type
        description: Enter BuildName / BuildVersion
        required: true
        default: '1.0.0'


jobs:
  debug:
    name: debug
    if: ${{ github.event.inputs.buildType == 'debug' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup JDK
        uses: actions/setup-java@v3.2.0
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jdk

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembledebug

      - name: Upload Apk
        uses: actions/upload-artifact@v3.0.0
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 3

      - name: upload artefact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: rranjan1-tataunistore.com/MP-Android-App
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: alpha
          file: app/build/outputs/apk/debug/app-debug.apk
          notifyTesters: true
          debug: true
