name: Manual Trigger Build

on:
  workflow_dispatch:
    inputs:
      buildType:
        type: choice
        description: Select Build type
        required: true
        default: 'debug'
        options:
          - debug
          - releaseDebug
          - release
          - appBundle

      version:
        type: build_type
        description: Enter BuildName / BuildVersion
        required: true
        default: '1.0.0'


jobs:
  debug:
    name: debug
    if: ${{ github.event.inputs.buildType == 'debug' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup JDK
        uses: actions/setup-java@v3.2.0
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jdk

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembledebug

      - name: Upload Apk
        uses: actions/upload-artifact@v3.0.0
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 3

      - name: upload artefact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: rranjan1-tataunistore.com/MP-Android-App
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: alpha
          file: app/build/outputs/apk/debug/app-debug.apk
          notifyTesters: true
          debug: true

  releaseDebug:
    name: releaseDebug
    if: ${{ github.event.inputs.buildType == 'releaseDebug' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup JDK
        uses: actions/setup-java@v3.2.0
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jdk

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate a ReleaseDebug Apk
        run: ./gradlew assemblereleaseDebug

      - name: Sign ReleaseDebug APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/releaseDebug
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload ReleaseDebug Apk
        uses: actions/upload-artifact@v3.0.0
        with:
          name: app-releaseDebug.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          retention-days: 3

  release:
    name: release
    if: ${{ github.event.inputs.buildType == 'release' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup JDK
        uses: actions/setup-java@v3.2.0
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jdk

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate a Release Apk
        run: ./gradlew assemblerelease

      - name: Sign Release APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app_release
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Release Apk
        uses: actions/upload-artifact@v3.0.0
        with:
          name: app-release.apk
          path: ${{steps.sign_app_release.outputs.signedReleaseFile}}
          retention-days: 3

  appBundle:
    name: appBundle
    if: ${{ github.event.inputs.buildType == 'appBundle' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Setup JDK
        uses: actions/setup-java@v3.2.0
        with:
          distribution: 'zulu'
          java-version: '11.0.12+7'
          java-package: jdk

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate a App Bundle
        run: ./gradlew bundleRelease

      - name: Sign App Bundle
        uses: r0adkll/sign-android-release@v1.0.4
        id: sign_app_bundle
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload App Bundle
        uses: actions/upload-artifact@v3.0.0
        with:
          name: app-release.aab
          path: ${{steps.sign_app_bundle.outputs.signedReleaseFile}}
          retention-days: 3

      - name : Internal Sharing Bundle Upload On Play Console
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.tul.tatacliq
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: draft